---
- name: Provision Bitwarden
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: 
          - docker
          - docker-compose
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
  tasks:
  - name: Create project directory
    file:
      path: /opt/app
      state: directory

  - name: Copy docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: /opt/app/docker-compose.yml

  - name: Start Compose
    docker_compose:
      project_src: /opt/app
      files:
        - docker-compose.yml

    